
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: "username"
  password: "password"

development:
  <<: *default
  database: store_development

test:
  <<: *default
  database: store_test


production:
  <<: *default
  database: store_production
  username: store
  password: <%= ENV['STORE_DATABASE_PASSWORD'] %>
