# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab682fd1d1a8da10e642f93fd7453813820a77dda0789bde28ef2607cf552a969915d78c8accb34b3d83c0e21a1faa55a41598d48a327a3dbd46b38ede97f2a3

test:
  secret_key_base: 6b4fa627f959ec1f4aab6dd357d3c13993f1d99bd9072452ee2364c1c470ca1a9295d80661de41995da5dd086ad32cf6450f7e5f58e136096ff4eeb2c7848738

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
